/**
 * NovaScope v2.0 — Export Engine
 * PDF · CSV · TXT with Nova branding
 * Nova Team · Hamza Samier · 2026
 */

'use strict';

const NOVA = {
  name:  'Hamza Samier',
  team:  'Nova Team',
  phone: '+20 122 776 8855',
  tag:   'NovaScope — Social Media Intelligence',
  // Brand colors matching the CSS palette
  blue:   [10, 132, 255],
  dark:   [10,  10,  20],
  surface:[26,  26,  30],
  txt:    [240, 240, 248],
  txt2:   [145, 144, 168],
  green:  [48, 209, 88],
  purple: [191, 90, 242],
  teal:   [90, 200, 250],
  orange: [255, 159, 10],
};

// Platform palette matches css/app
const PLT_COLORS = [
  [10, 132, 255],[191, 90, 242],[255, 55, 95],[48, 209, 88],
  [255, 159, 10],[90, 200, 250],[255, 214, 10],[255, 107, 107],
];

// ════════════════════════════════════════════════════
// PDF EXPORT — Dark/Blue themed
// ════════════════════════════════════════════════════
async function exportPDF(reportData, selectedItems, selectedCharts) {
  const btn = el('exportGoBtn');
  if (btn) {
    btn.disabled = true;
    const span = btn.querySelector('span');
    if (span) span.textContent = currentLang === 'ar' ? 'جارٍ التوليد…' : 'Generating…';
  }

  const template = el('pdfExportTemplate');
  if (!template) return;
  template.innerHTML = '';
  template.setAttribute('dir', currentLang === 'ar' ? 'rtl' : 'ltr');

  try {
    const { jsPDF } = window.jspdf;
    
    // ── Build Pages in DOM ───────────────────────────
    
    // 1. Cover Page
    const cover = document.createElement('div');
    cover.className = 'pdf-page pdf-cover';
    cover.innerHTML = `
      <div class="pdf-cover-body">
        <div class="pdf-brand-full">Nova<span class="pdf-brand-accent">Scope</span></div>
        <div class="pdf-tag-line">Social Media Intelligence · Intelligence Report</div>
        <div class="pdf-divider"></div>
        <div class="pdf-report-title">${sanitize(reportData?.title || 'Digital Report')}</div>
      </div>
      <div class="pdf-cover-footer">
        <div class="pdf-meta-col">
          <span class="pdf-meta-lbl">Report Date</span>
          <span class="pdf-meta-val">${new Date().toLocaleDateString(currentLang === 'ar' ? 'ar-EG' : 'en-GB', { day: 'numeric', month: 'long', year: 'numeric' })}</span>
        </div>
        <div class="pdf-meta-col">
          <span class="pdf-meta-lbl">Generated By</span>
          <span class="pdf-meta-val">${sanitize(NOVA.name)}</span>
        </div>
        <div class="pdf-meta-col">
          <span class="pdf-meta-lbl">Version</span>
          <span class="pdf-meta-val">NovaScope v3.0</span>
        </div>
      </div>
    `;
    template.appendChild(cover);

    // 2. Metrics Page (if data selected)
    if (selectedItems.length > 0) {
      const page = document.createElement('div');
      page.className = 'pdf-page';
      page.innerHTML = `
        <div class="pdf-heading">
          <div class="pdf-h-blue"></div>
          <div class="pdf-h-text">${currentLang === 'ar' ? 'المؤشرات الرئيسية' : 'Key Metrics Overview'}</div>
        </div>
        <div class="pdf-metric-grid">
          ${selectedItems.map(item => `
            <div class="pdf-metric-card">
              <div class="pdf-m-label">${sanitize(item.label)}</div>
              <div class="pdf-m-value">${sanitize(item.value)}</div>
            </div>
          `).join('')}
        </div>
        <div class="pdf-footer">
          <span>NovaScope · Marketing Intelligence Report</span>
          <span class="pdf-pg-num">Page 2</span>
        </div>
      `;
      template.appendChild(page);
    }

    // 3. Platform Breakdown (if data exists)
    if (reportData?.platforms?.length) {
      const page = document.createElement('div');
      page.className = 'pdf-page';
      
      const sorted = [...reportData.platforms].sort((a, b) => b.users - a.users).slice(0, 12);
      const max   = sorted[0].users;

      page.innerHTML = `
        <div class="pdf-heading">
          <div class="pdf-h-blue"></div>
          <div class="pdf-h-text">${currentLang === 'ar' ? 'توزيع المنصات' : 'Social Platform Breakdown'}</div>
        </div>
        <div class="pdf-platform-list">
          ${sorted.map((p, i) => {
            const pct = (p.users / max) * 100;
            const clr = `rgb(${PLT_COLORS[i % PLT_COLORS.length].join(',')})`;
            return `
              <div class="pdf-p-row">
                <div class="pdf-p-name">${sanitize(p.name)}</div>
                <div class="pdf-p-bar-bg">
                  <div class="pdf-p-bar-fill" style="width:${pct}%; background:${clr}"></div>
                </div>
                <div class="pdf-p-val">${p.users}M ${p.growth ? `<small style="color:#30d158; margin-left:5px">+${p.growth}%</small>` : ''}</div>
              </div>
            `;
          }).join('')}
        </div>
        <div class="pdf-footer">
          <span>NovaScope · Intelligence Report</span>
          <span class="pdf-pg-num">Page ${selectedItems.length > 0 ? 3 : 2}</span>
        </div>
      `;
      template.appendChild(page);
    }

    // 4. Chart Pages (one chart per page for impact)
    const chartCanvases = [];
    for (const chartKey of selectedCharts) {
      const def = getSingleChartDef(chartKey, currentData);
      if (!def) continue;

      const page = document.createElement('div');
      page.className = 'pdf-page';
      page.innerHTML = `
        <div class="pdf-heading">
          <div class="pdf-h-blue"></div>
          <div class="pdf-h-text">${sanitize(def.title)}</div>
        </div>
        <div class="pdf-tag-line" style="margin-bottom:20px">${sanitize(def.subtitle)}</div>
        <div class="pdf-chart-box">
          <canvas id="pdf_chart_${chartKey}" width="600" height="350"></canvas>
        </div>
        <div class="pdf-footer">
          <span>NovaScope · Visual Analytics</span>
          <span class="pdf-pg-num"></span>
        </div>
      `;
      template.appendChild(page);
      chartCanvases.push({ key: chartKey, config: def.config });
    }

    // Render Charts into the template
    for (const c of chartCanvases) {
      const canvas = document.getElementById(`pdf_chart_${c.key}`);
      if (canvas) {
        // High DPI for charts
        new Chart(canvas, {
          ...c.config,
          options: {
            ...c.config.options,
            animation: false,
            responsive: false,
            devicePixelRatio: 2
          }
        });
      }
    }

    // Give browser time to paint
    await new Promise(r => setTimeout(r, 600));

    // ── Capture and PDF Generation ───────────────────
    
    const doc = new jsPDF({ orientation: 'p', unit: 'mm', format: 'a4', compress: true });
    const pages = template.querySelectorAll('.pdf-page');

    for (let i = 0; i < pages.length; i++) {
      if (i > 0) doc.addPage();
      
      const canvas = await html2canvas(pages[i], {
        scale: 2, // High resolution
        useCORS: true,
        backgroundColor: '#0a0a14',
        logging: false,
      });

      const imgData = canvas.toDataURL('image/jpeg', 0.9);
      const imgProps = doc.getImageProperties(imgData);
      const pdfW = doc.internal.pageSize.getWidth();
      const pdfH = (imgProps.height * pdfW) / imgProps.width;

      doc.addImage(imgData, 'JPEG', 0, 0, pdfW, pdfH);
      
      // Update page numbers in footer post-capture? 
      // Better to have done it in the loop before capture.
    }

    // Save
    const country  = (reportData?.country || 'report').replace(/\s+/g, '_').toLowerCase();
    const dateSlug = new Date().toISOString().slice(0, 10);
    doc.save(`novascope_${country}_${dateSlug}.pdf`);

  } catch (err) {
    console.error('[NovaScope PDF Engine Error]', err);
    alert('High-fidelity PDF export failed. Falling back to basic mode or try again.');
  } finally {
    template.innerHTML = ''; // Clean up
    if (btn) {
      btn.disabled = false;
      const span = btn.querySelector('span');
      if (span) span.textContent = currentLang === 'ar' ? 'تصدير التقرير' : 'Export Report';
    }
  }
}

// ════════════════════════════════════════════════════
// CSV EXPORT
// ════════════════════════════════════════════════════
function exportCSV(reportData, selectedItems) {
  const q = v => `"${String(v ?? '').replace(/"/g, '""')}"`;
  const rows = [
    ['NovaScope Export'],
    ['Report', reportData?.title || ''],
    ['Country', reportData?.country || ''],
    ['Source', reportData?.sourceUrl || 'datareportal.com'],
    ['Generated', new Date().toLocaleString()],
    ['Generated by', `${NOVA.name} · ${NOVA.phone}`],
    [],
    ['METRIC', 'VALUE'],
    ...selectedItems.map(i => [i.label, i.value]),
    [],
    ['PLATFORM', 'USERS (M)', 'GROWTH (%)'],
    ...(reportData?.platforms || []).map(p => [
      p.name, p.users, p.growth != null ? '+' + p.growth : 'N/A',
    ]),
    [],
    ['Generated by Nova', NOVA.name, NOVA.phone],
  ];

  const csv = rows.map(r => r.map(q).join(',')).join('\r\n');
  const fname = `novascope_${(reportData?.country || 'report').replace(/\s+/g, '_').toLowerCase()}.csv`;
  triggerDownload(csv, fname, 'text/csv;charset=utf-8;');
}

// ════════════════════════════════════════════════════
// TXT EXPORT
// ════════════════════════════════════════════════════
function exportTXT(reportData, selectedItems) {
  const bar = (char, n) => char.repeat(n);
  const lines = [
    bar('═', 52),
    '         NovaScope — Social Media Intelligence',
    bar('═', 52),
    '',
    `Report  : ${reportData?.title  || 'N/A'}`,
    `Country : ${reportData?.country || 'N/A'}`,
    `Date    : ${new Date().toLocaleString()}`,
    `Source  : ${reportData?.sourceUrl || 'datareportal.com'}`,
    '',
    bar('─', 52),
    'METRICS',
    bar('─', 52),
    ...selectedItems.map(i => `  ${i.label.padEnd(32)} ${i.value}`),
    '',
  ];

  if (reportData?.platforms?.length) {
    lines.push(bar('─', 52));
    lines.push('PLATFORM BREAKDOWN');
    lines.push(bar('─', 52));
    reportData.platforms.forEach(p => {
      const g = p.growth != null ? ` (+${p.growth}%)` : '';
      lines.push(`  ${p.name.padEnd(18)} ${String(p.users + 'M').padStart(8)}${g}`);
    });
    lines.push('');
  }

  lines.push(bar('─', 52));
  lines.push('Generated by Nova');
  lines.push(`Developer : ${NOVA.name}`);
  lines.push(`WhatsApp  : ${NOVA.phone}`);
  lines.push(`Tool      : ${NOVA.tag}`);
  lines.push(bar('═', 52));

  const fname = `novascope_${(reportData?.country || 'report').replace(/\s+/g, '_').toLowerCase()}.txt`;
  triggerDownload(lines.join('\n'), fname, 'text/plain;charset=utf-8;');
}

// ════════════════════════════════════════════════════
// HELPERS
// ════════════════════════════════════════════════════
function triggerDownload(content, filename, mime) {
  const blob = new Blob([content], { type: mime });
  const url  = URL.createObjectURL(blob);
  const a    = Object.assign(document.createElement('a'), { href: url, download: filename });
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  setTimeout(() => URL.revokeObjectURL(url), 3000);
}
