/**
 * NovaScope v2.0 — Export Engine
 * PDF · CSV · TXT with Nova branding
 * Nova Team · Hamza Samier · 2026
 */

'use strict';

const NOVA = {
  name:  'Hamza Samier',
  team:  'Nova Team',
  phone: '+20 122 776 8855',
  tag:   'NovaScope — Social Media Intelligence',
  // Brand colors matching the CSS palette
  blue:   [10, 132, 255],
  dark:   [10,  10,  20],
  surface:[26,  26,  30],
  txt:    [240, 240, 248],
  txt2:   [145, 144, 168],
  green:  [48, 209, 88],
  purple: [191, 90, 242],
  teal:   [90, 200, 250],
  orange: [255, 159, 10],
};

// Platform palette matches css/app
const PLT_COLORS = [
  [10, 132, 255],[191, 90, 242],[255, 55, 95],[48, 209, 88],
  [255, 159, 10],[90, 200, 250],[255, 214, 10],[255, 107, 107],
];

// ════════════════════════════════════════════════════
// PDF EXPORT — Dark/Blue themed
// ════════════════════════════════════════════════════
async function exportPDF(reportData, selectedItems, selectedCharts) {
  const btn = el('exportGoBtn');
  if (btn) {
    btn.disabled = true;
    const span = btn.querySelector('span');
    if (span) span.textContent = currentLang === 'ar' ? 'جارٍ التوليد…' : 'Generating…';
  }

  try {
    const { jsPDF } = window.jspdf;
    const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
    const W = doc.internal.pageSize.getWidth();
    const H = doc.internal.pageSize.getHeight();
    const mg = 16; // margin
    let y = mg;

    // ── Helpers ────────────────────────────────────────
    const rgb  = (...c) => doc.setTextColor(...c);
    const fill = (...c) => doc.setFillColor(...c);
    const draw = (...c) => doc.setDrawColor(...c);
    const font = (fam, style, size) => {
      doc.setFont(fam, style);
      doc.setFontSize(size);
    };
    const textAt = (text, x, yPos, opts = {}) => {
      doc.text(String(text), x, yPos, opts);
    };

    const hline = (yPos, r = 50, g = 50, b = 60, thick = 0.3) => {
      draw(r, g, b);
      doc.setLineWidth(thick);
      doc.line(mg, yPos, W - mg, yPos);
    };

    const ensurePage = (needed = 14) => {
      if (y + needed > H - 18) {
        addFooter(doc, W, H, mg, reportData);
        doc.addPage();
        y = mg;
        addRunningHeader(doc, W, mg, reportData);
        y += 14;
      }
    };

    // ── PAGE 1: Cover ───────────────────────────────────
    // Full dark background
    fill(...NOVA.dark);
    doc.rect(0, 0, W, H, 'F');

    // Blue top band
    fill(...NOVA.blue);
    doc.rect(0, 0, W, 52, 'F');

    // NovaScope wordmark
    font('helvetica', 'bold', 20);
    rgb(255, 255, 255);
    textAt('NovaScope', mg, 22);

    font('helvetica', 'normal', 8);
    rgb(200, 225, 255);
    textAt('Social Media Intelligence · by Hamza Samier', mg, 30);

    // Divider line in blue band
    draw(255, 255, 255);
    doc.setLineWidth(0.3);
    doc.line(mg, 35, W - mg, 35);

    // Report info in band
    const flag = getCountryFlag(reportData?.sourceUrl || '');
    font('helvetica', 'bold', 10);
    rgb(255, 255, 255);
    textAt(`${flag}  ${reportData?.title || 'Digital Report'}`, mg, 46);

    // Dark card area below cover band
    const cardY = 62;
    fill(26, 26, 30);
    doc.roundedRect(mg, cardY, W - mg * 2, 50, 3, 3, 'F');

    font('helvetica', 'normal', 8);
    rgb(...NOVA.txt2);
    textAt('Report Date', mg + 10, cardY + 10);
    textAt('Source', mg + 10, cardY + 20);
    textAt('Data Provider', mg + 10, cardY + 30);
    textAt('Generated by', mg + 10, cardY + 40);

    font('helvetica', 'bold', 8);
    rgb(...NOVA.txt);
    const dateStr = new Date().toLocaleDateString('en-GB', { day: '2-digit', month: 'long', year: 'numeric' });
    textAt(dateStr,             mg + 55, cardY + 10);
    textAt('datareportal.com',  mg + 55, cardY + 20);
    textAt('DataReportal',      mg + 55, cardY + 30);
    textAt('NovaScope v2.0',    mg + 55, cardY + 40);

    // Summary stats row
    const statsY = cardY + 58;
    const statW  = (W - mg * 2) / 3;

    const statsData = [
      { label: 'Data Points', val: selectedItems.length || '0' },
      { label: 'Platforms',   val: String(reportData?.platforms?.length || 0) },
      { label: 'Charts',      val: String(selectedCharts.length) },
    ];
    statsData.forEach((s, i) => {
      const sx = mg + i * statW;
      fill(...NOVA.surface);
      doc.roundedRect(sx, statsY, statW - 4, 22, 2, 2, 'F');
      font('helvetica', 'bold', 14);
      rgb(...NOVA.blue);
      textAt(s.val, sx + (statW - 4) / 2, statsY + 11, { align: 'center' });
      font('helvetica', 'normal', 7);
      rgb(...NOVA.txt2);
      textAt(s.label, sx + (statW - 4) / 2, statsY + 18, { align: 'center' });
    });

    addFooter(doc, W, H, mg, reportData);

    // ── PAGE 2: Key Metrics ─────────────────────────────
    doc.addPage();
    fill(...NOVA.dark);
    doc.rect(0, 0, W, H, 'F');
    addRunningHeader(doc, W, mg, reportData);
    y = mg + 14;

    // Section heading
    sectionHeading(doc, 'Key Metrics', mg, y, W);
    y += 12;

    if (selectedItems.length === 0) {
      font('helvetica', 'normal', 9);
      rgb(...NOVA.txt2);
      textAt('No data items selected.', mg, y);
      y += 10;
    } else {
      const colW = (W - mg * 2 - 6) / 2;

      selectedItems.forEach((item, i) => {
        const col  = i % 2;
        const row  = Math.floor(i / 2);
        const cx   = mg + col * (colW + 6);
        const cy   = y + row * 28;

        ensurePage(30);
        if (col === 0 && i > 0) y = cy; // update y tracker every new row

        const color = PLT_COLORS[i % PLT_COLORS.length];
        fill(color[0], color[1], color[2], 0.1);
        doc.roundedRect(cx, cy, colW, 22, 2, 2, 'F');

        // Left accent bar
        fill(...color);
        doc.roundedRect(cx, cy, 2.5, 22, 1, 1, 'F');

        font('helvetica', 'normal', 7);
        rgb(...NOVA.txt2);
        const labelLines = doc.splitTextToSize(item.label, colW - 16);
        textAt(labelLines[0], cx + 7, cy + 7);

        font('helvetica', 'bold', 13);
        rgb(...NOVA.txt);
        textAt(String(item.value), cx + 7, cy + 17);
      });

      // Advance y past the grid
      const rows = Math.ceil(selectedItems.length / 2);
      y += rows * 28 + 8;
    }

    // ── PAGE 3: Platform Breakdown ─────────────────────
    if (reportData?.platforms?.length) {
      ensurePage(40);
      sectionHeading(doc, 'Platform Breakdown', mg, y, W);
      y += 12;

      const sorted = [...reportData.platforms].sort((a, b) => b.users - a.users).slice(0, 10);
      const maxU   = sorted[0].users;
      const barW   = W - mg * 2 - 52;

      sorted.forEach((p, i) => {
        ensurePage(10);
        const fillPct = p.users / maxU;
        const clr     = PLT_COLORS[i % PLT_COLORS.length];

        // Row bg
        if (i % 2 === 0) {
          fill(26, 26, 30);
          doc.rect(mg, y - 4, W - mg * 2, 9, 'F');
        }

        // Platform name
        font('helvetica', i === 0 ? 'bold' : 'normal', 8);
        rgb(...NOVA.txt);
        textAt(p.name.substring(0, 14), mg + 2, y + 2);

        // Bar background
        fill(40, 40, 50);
        doc.roundedRect(mg + 38, y - 2, barW, 5, 1, 1, 'F');

        // Bar fill
        fill(...clr);
        const fw = Math.max(1, fillPct * barW);
        doc.roundedRect(mg + 38, y - 2, fw, 5, 1, 1, 'F');

        // Value label
        font('helvetica', 'bold', 8);
        rgb(...NOVA.txt);
        textAt(p.users + 'M', mg + 38 + barW + 4, y + 2);

        // Growth
        if (p.growth != null) {
          font('helvetica', 'normal', 7);
          rgb(...NOVA.green);
          textAt(`+${p.growth}%`, W - mg - 2, y + 2, { align: 'right' });
        }

        y += 10;
      });
    }

    // ── CHART PAGES ─────────────────────────────────────
    for (const chartKey of selectedCharts) {
      const def = getSingleChartDef(chartKey, currentData);
      if (!def) continue;

      try {
        // Render chart to off-screen canvas
        const offCanvas = document.createElement('canvas');
        offCanvas.width  = 800;
        offCanvas.height = 400;
        offCanvas.style.cssText = 'position:fixed;top:-9999px;left:-9999px;background:#1c1c1e';
        document.body.appendChild(offCanvas);

        // Give it a dark bg canvas context fill
        const ctx2d = offCanvas.getContext('2d');
        ctx2d.fillStyle = '#1c1c1e';
        ctx2d.fillRect(0, 0, offCanvas.width, offCanvas.height);

        destroyChart('__pdfCanvas');
        registerChart('__pdfCanvas', new Chart(offCanvas, def.config));
        await new Promise(r => setTimeout(r, 300));

        const imgData = offCanvas.toDataURL('image/png', 0.92);

        doc.addPage();
        fill(...NOVA.dark);
        doc.rect(0, 0, W, H, 'F');
        addRunningHeader(doc, W, mg, reportData);
        y = mg + 14;

        sectionHeading(doc, def.title, mg, y, W);
        y += 7;

        font('helvetica', 'normal', 8);
        rgb(...NOVA.txt2);
        textAt(def.subtitle, mg, y);
        y += 8;

        doc.addImage(imgData, 'PNG', mg, y, W - mg * 2, 85);
        y += 90;

        destroyChart('__pdfCanvas');
        document.body.removeChild(offCanvas);
      } catch (e) {
        console.warn('[NovaScope PDF] Chart failed:', e);
      }
    }

    // ── FINAL PAGE: Nova Branding ────────────────────────
    doc.addPage();
    fill(...NOVA.dark);
    doc.rect(0, 0, W, H, 'F');

    // Blue gradient-like band at top
    fill(...NOVA.blue);
    doc.rect(0, 0, W, 40, 'F');

    // Try to embed Nova logo
    try {
      const logoDataURL = await loadLogoDataURL('css/NOVA Mono logo.png');
      const lW = 70, lH = 28;
      // Place on white swatch so dark logo shows
      fill(250, 250, 252);
      doc.roundedRect((W - lW) / 2 - 5, 60, lW + 10, lH + 6, 4, 4, 'F');
      doc.addImage(logoDataURL, 'PNG', (W - lW) / 2, 63, lW, lH);
    } catch (_) {
      // Fallback text logo
      font('helvetica', 'bold', 22);
      rgb(...NOVA.blue);
      textAt('NovaScope', W / 2, 80, { align: 'center' });
    }

    const cy2 = 105;

    font('helvetica', 'bold', 11);
    rgb(...NOVA.txt);
    textAt('Generated by Nova', W / 2, cy2, { align: 'center' });

    fill(...NOVA.blue);
    doc.roundedRect(W / 2 - 30, cy2 + 3, 60, 0.5, 0.25, 0.25, 'F');

    font('helvetica', 'bold', 10);
    rgb(...NOVA.txt);
    textAt(NOVA.name, W / 2, cy2 + 12, { align: 'center' });

    font('helvetica', 'normal', 9);
    rgb(...NOVA.blue);
    textAt(NOVA.phone, W / 2, cy2 + 20, { align: 'center' });

    font('helvetica', 'normal', 7);
    rgb(...NOVA.txt2);
    textAt(NOVA.tag, W / 2, cy2 + 30, { align: 'center' });
    textAt(dateStr ?? new Date().toLocaleDateString(), W / 2, cy2 + 38, { align: 'center' });

    addFooter(doc, W, H, mg, reportData);

    // Save
    const country  = (reportData?.country || 'report').replace(/\s+/g, '_').toLowerCase();
    const dateSlug = new Date().toISOString().slice(0, 10);
    doc.save(`novascope_${country}_${dateSlug}.pdf`);

  } catch (err) {
    console.error('[NovaScope PDF]', err);
    alert('PDF export failed. Please try again.');
  } finally {
    if (btn) {
      btn.disabled = false;
      const span = btn.querySelector('span');
      if (span) span.textContent = currentLang === 'ar' ? 'تصدير التقرير' : 'Export Report';
    }
  }
}

// ── PDF Page helpers ────────────────────────────────
function addRunningHeader(doc, W, mg, reportData) {
  const { jsPDF } = window.jspdf;
  doc.setFillColor(...NOVA.blue);
  doc.rect(0, 0, W, 8, 'F');
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(6);
  doc.setTextColor(200, 225, 255);
  doc.text('NovaScope · ' + (reportData?.title || 'Report'), mg, 6);
  doc.text(new Date().toLocaleDateString(), W - mg, 6, { align: 'right' });
}

function addFooter(doc, W, H, mg, reportData) {
  doc.setFontSize(6);
  doc.setTextColor(...NOVA.txt2);
  doc.setFont('helvetica', 'normal');
  doc.text(`Generated by Nova · ${NOVA.name} · ${NOVA.phone}`, mg, H - 6);
  doc.text(`Page ${doc.internal.getCurrentPageInfo().pageNumber}`, W - mg, H - 6, { align: 'right' });
  doc.setDrawColor(50, 50, 60);
  doc.setLineWidth(0.2);
  doc.line(mg, H - 10, W - mg, H - 10);
}

function sectionHeading(doc, text, x, y, W) {
  doc.setFillColor(...NOVA.blue);
  doc.rect(x, y - 2, 2.5, 8, 'F');
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(10);
  doc.setTextColor(...NOVA.txt);
  doc.text(text, x + 6, y + 5);
  doc.setDrawColor(40, 40, 55);
  doc.setLineWidth(0.2);
  doc.line(x + 6 + doc.getTextWidth(text) + 4, y + 2, W - x, y + 2);
}

function loadLogoDataURL(src) {
  return new Promise((resolve, reject) => {
    const img    = new Image();
    img.crossOrigin = 'anonymous';
    img.onload = () => {
      const c   = document.createElement('canvas');
      c.width   = img.naturalWidth;
      c.height  = img.naturalHeight;
      c.getContext('2d').drawImage(img, 0, 0);
      resolve(c.toDataURL('image/png'));
    };
    img.onerror = reject;
    img.src     = src + '?cb=' + Date.now();
  });
}

// ════════════════════════════════════════════════════
// CSV EXPORT
// ════════════════════════════════════════════════════
function exportCSV(reportData, selectedItems) {
  const q = v => `"${String(v ?? '').replace(/"/g, '""')}"`;
  const rows = [
    ['NovaScope Export'],
    ['Report', reportData?.title || ''],
    ['Country', reportData?.country || ''],
    ['Source', reportData?.sourceUrl || 'datareportal.com'],
    ['Generated', new Date().toLocaleString()],
    ['Generated by', `${NOVA.name} · ${NOVA.phone}`],
    [],
    ['METRIC', 'VALUE'],
    ...selectedItems.map(i => [i.label, i.value]),
    [],
    ['PLATFORM', 'USERS (M)', 'GROWTH (%)'],
    ...(reportData?.platforms || []).map(p => [
      p.name, p.users, p.growth != null ? '+' + p.growth : 'N/A',
    ]),
    [],
    ['Generated by Nova', NOVA.name, NOVA.phone],
  ];

  const csv = rows.map(r => r.map(q).join(',')).join('\r\n');
  const fname = `novascope_${(reportData?.country || 'report').replace(/\s+/g, '_').toLowerCase()}.csv`;
  triggerDownload(csv, fname, 'text/csv;charset=utf-8;');
}

// ════════════════════════════════════════════════════
// TXT EXPORT
// ════════════════════════════════════════════════════
function exportTXT(reportData, selectedItems) {
  const bar = (char, n) => char.repeat(n);
  const lines = [
    bar('═', 52),
    '         NovaScope — Social Media Intelligence',
    bar('═', 52),
    '',
    `Report  : ${reportData?.title  || 'N/A'}`,
    `Country : ${reportData?.country || 'N/A'}`,
    `Date    : ${new Date().toLocaleString()}`,
    `Source  : ${reportData?.sourceUrl || 'datareportal.com'}`,
    '',
    bar('─', 52),
    'METRICS',
    bar('─', 52),
    ...selectedItems.map(i => `  ${i.label.padEnd(32)} ${i.value}`),
    '',
  ];

  if (reportData?.platforms?.length) {
    lines.push(bar('─', 52));
    lines.push('PLATFORM BREAKDOWN');
    lines.push(bar('─', 52));
    reportData.platforms.forEach(p => {
      const g = p.growth != null ? ` (+${p.growth}%)` : '';
      lines.push(`  ${p.name.padEnd(18)} ${String(p.users + 'M').padStart(8)}${g}`);
    });
    lines.push('');
  }

  lines.push(bar('─', 52));
  lines.push('Generated by Nova');
  lines.push(`Developer : ${NOVA.name}`);
  lines.push(`WhatsApp  : ${NOVA.phone}`);
  lines.push(`Tool      : ${NOVA.tag}`);
  lines.push(bar('═', 52));

  const fname = `novascope_${(reportData?.country || 'report').replace(/\s+/g, '_').toLowerCase()}.txt`;
  triggerDownload(lines.join('\n'), fname, 'text/plain;charset=utf-8;');
}

// ════════════════════════════════════════════════════
// HELPERS
// ════════════════════════════════════════════════════
function triggerDownload(content, filename, mime) {
  const blob = new Blob([content], { type: mime });
  const url  = URL.createObjectURL(blob);
  const a    = Object.assign(document.createElement('a'), { href: url, download: filename });
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  setTimeout(() => URL.revokeObjectURL(url), 3000);
}
